name: CI (windows)
on: [push, pull_request]

jobs:
    msvc-openssl:
        runs-on: windows-latest
        outputs:
            openssl-head: ${{ steps.openssl.outputs.head }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/checkout@v2
              with:
                  repository: openssl/openssl
                  path: openssl
                  ref: openssl-3.6.0
                  fetch-depth: 0
            - run: echo "::set-output name=head::$(git -C openssl describe --always --long)"
              id: openssl
            - uses: actions/cache@v4
              id: cache
              with:
                  path: openssl/_dest
                  key: ${{ runner.os }}-openssl-${{ steps.openssl.outputs.head }}
            - name: Apply patches
              run: |
                  git apply patches/openssl-tls1.3.patch
            - uses: ilammy/msvc-dev-cmd@v1
            - name: Build OpenSSL
              working-directory: openssl
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
                  perl Configure no-makedepend no-tests no-asm VC-WIN64A
                  perl configdata.pm --dump
                  nmake /S build_libs build_programs
                  nmake /S install_sw DESTDIR=_dest

    msvc-engine:
        needs: msvc-openssl
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - uses: actions/cache@v4
              with:
                  path: openssl/_dest
                  key: ${{ runner.os }}-openssl-${{ needs.msvc-openssl.outputs.openssl-head }}
            - run: cmake -DOPENSSL_ROOT_DIR="openssl\_dest\Program Files\OpenSSL" -DOPENSSL_ENGINES_DIR=bin .
            - run: cmake --build .
            - name: Run tests
              run: |
                  $env:OPENSSL_ENGINES = "$pwd\bin\Debug"
                  $env:OPENSSL_MODULES = "$pwd\bin\Debug"
                  Copy-Item -Path "$pwd\openssl\_dest\Program Files\OpenSSL\bin\*.dll" -Destination "$pwd\bin\Debug"
                  ctest -C Debug --output-on-failure
            - name: Compress binaries
              run: |
                  mkdir "openssl\release"
                  (robocopy "openssl\_dest\Program Files\OpenSSL\" openssl\release *.dll *.exe *.cnf /S) ^& IF %ERRORLEVEL% LSS 8 SET ERRORLEVEL = 0
                  if ($lastexitcode -ge 8) { exit 1 }
                  Copy-Item -Path "$pwd\bin\Debug\gost.dll" -Destination "$pwd\openssl\release\lib\engines-3\"
                  Copy-Item -Path "$pwd\bin\Debug\gostprov.dll" -Destination "$pwd\openssl\release\lib\ossl-modules\"
                  Compress-Archive "$pwd\openssl\release" "$pwd\openssl\release.zip"
            - name: Upload to Release
              uses: softprops/action-gh-release@v1
              with:
               files: |
                 openssl/release.zip
               name: OpenSSL_With_GostEngine_${{ env.BUILD_DATE }}.zip
               tag_name: ${{ github.run_id }}
               body: |
